header-from: "docs/.header.md"

formatter: markdown table
output:
  file: "README.md"
  mode: inject

settings:
  indent: 2
  escape: true
  show: true
  hide-empty: true

sections:
  include:
    - header
    - requirements
    - providers
    - inputs
    - outputs
    - modules
    - resources
    - dependencies
    - footer

  hide:

sort:
  enabled: true
  by: name

templates:
  header: |
    # {{ .Module.Name }}

    {{ if .Module.Description }}{{ .Module.Description }}
    {{ else }}Documentation pour le module Terraform `{{ .Module.Name }}`.
    {{ end }}

  footer: |
    _Généré par [terraform-docs](https://terraform-docs.io)_